habapi_Category:
    type: rest
    resource: HabApiBundle\Controller\CategoryController

habapi_Budget:
    type: rest
    resource: HabApiBundle\Controller\BudgetController

habapi_Validate:
    type: rest
    resource: HabApiBundle\Controller\ValidateController
