<?php

namespace HabApiBundle\Repository;

use HabApiBundle\Entity\User;

/**
 * BudgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPaginated($user, $limit = null, $offset = null)
    {
        $em = $this->getEntityManager();
        $repository = $em->getRepository('HabApiBundle:Budget');
        $qb = $repository->createQueryBuilder('b');
        $qb->select('b');

        if ($user instanceof User) {
            $qb
                ->where('b.user = :user')
                ->setParameter('user', $user)
            ;
        }

        $qb->setFirstResult($offset);
        if (0 < $limit) {
            $qb->setMaxResults($limit);
        }

        return $qb
            ->getQuery()
            ->execute()
        ;
    }
}
